stages:
  to-pandas-pickle:
    cmd: python ./to_pandas.py -i ./data/raw_data/chgk.zip -o ./data/pickle_data
    deps:
    - ./data/raw_data/chgk.zip
    - ./to_pandas.py
    outs:
    - ./data/pickle_data
  filter-team-res:
    cmd: python ./filter_results.py -i ./data/raw_data/chgk.zip --tournaments ./data/pickle_data/tournaments-dt.pickle
      -o ./data/team_res
    deps:
    - ./data/pickle_data/tournaments-dt.pickle
    - ./filter_results.py
    outs:
    - ./data/team_res
